version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: redisCaching-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: redisCaching
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    command: ["redis-server", "--save", "", "--appendonly", "no"]

networks:
  app-network:
    driver: bridge