spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/redisCaching
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379

  elasticsearch:
    uris: http://elasticsearch:9200

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: demo-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: record
      concurrency: 1
      type: single
      missing-topics-fatal: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  topic: my-first-topic
  dlt-topic: product-updates.DLT
