spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/redisCaching
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379
