apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-caching-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-caching
  template:
    metadata:
      labels:
        app: redis-caching
    spec:
      containers:
        - name: redis-caching-container
          image: sonabiju/redis-caching-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/redisCaching
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_ELASTICSEARCH_URIS
              value: http://elasticsearch:9200
            - name: SPRING_PROFILES_ACTIVE
              value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: redis-caching-app
spec:
  selector:
    app: redis-caching
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
